# Generated by Django 4.0.2 on 2022-02-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaracterizacaoDeCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('modalidade_do_curso', models.CharField(max_length=100)),
                ('classificacao_do_curso', models.CharField(max_length=100)),
                ('programa_de_formacao', models.CharField(max_length=1000)),
                ('conteudo_programatico_do_curso', models.CharField(max_length=1000)),
                ('periodos_de_oferta_do_curso_nos_proximos_5_anos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CaracterizacaoDeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_do_evento_em_numero_de_dias', models.IntegerField()),
                ('quantitativo_de_publico', models.IntegerField()),
                ('numero_da_edicao_do_evento', models.IntegerField()),
                ('tema_geral_do_evento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CaracterizacaoDeProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologia', models.CharField(max_length=10000)),
                ('duracao_pretendida_do_projeto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadoresAdjuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('centro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscolaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_de_escola', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesDaAcaoDeExtensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=1000)),
                ('modalidade', models.CharField(max_length=100)),
                ('area_tematica_principal', models.CharField(max_length=100)),
                ('area_tematica_secundaria', models.CharField(max_length=100)),
                ('objetivos_de_desenvolvimento_sustentavel', models.CharField(max_length=100)),
                ('coordenador_da_acao_de_extensao', models.CharField(max_length=100)),
                ('Resumo', models.CharField(max_length=1000)),
                ('Contato', models.CharField(max_length=100)),
                ('data_de_inicio', models.DateField()),
                ('data_de_termino', models.DateField()),
                ('objetivos', models.CharField(max_length=1000)),
                ('links_para_redes_sociaus_e_sites', models.CharField(max_length=1000)),
                ('endereco', models.CharField(max_length=1000)),
                ('publico_da_acao', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaosParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_de_parceiro', models.CharField(max_length=100)),
                ('forma_de_institucionalizacao', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=1000)),
                ('tipo_de_instituicao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('periodo_de_participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='CaracterizacaoDePrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoes_de_extensao_vinculadas', models.ManyToManyField(to='scraper.Acao')),
                ('coordenadores_adjuntos', models.ManyToManyField(to='scraper.CoordenadoresAdjuntos')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='equipe_de_realizacao',
            field=models.ManyToManyField(to='scraper.Membro'),
        ),
        migrations.AddField(
            model_name='acao',
            name='escolas_participantes',
            field=models.ManyToManyField(to='scraper.EscolaParticipante'),
        ),
        migrations.AddField(
            model_name='acao',
            name='informacoes_da_acao_de_extensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.informacoesdaacaodeextensao'),
        ),
        migrations.AddField(
            model_name='acao',
            name='instituicoes_parceiras',
            field=models.ManyToManyField(to='scraper.InstituicaosParceira'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('acao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.acao')),
                ('caracterizacao_de_projetos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.caracterizacaodeprojeto')),
            ],
            bases=('scraper.acao',),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('acao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.acao')),
                ('caracterizacao_de_programas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.caracterizacaodeprograma')),
            ],
            bases=('scraper.acao',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('acao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.acao')),
                ('caracterizacao_de_eventos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.caracterizacaodeevento')),
            ],
            bases=('scraper.acao',),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('acao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scraper.acao')),
                ('caracterizacao_de_cursos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scraper.caracterizacaodecurso')),
            ],
            bases=('scraper.acao',),
        ),
    ]
