# Generated by Django 4.0.2 on 2022-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_acao_id_alter_informacoesdaacaodeextensao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacaodecurso',
            name='carga_horaria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='informacoesdaacaodeextensao',
            name='carga_horaria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='informacoesdaacaodeextensao',
            name='data_de_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informacoesdaacaodeextensao',
            name='data_de_termino',
            field=models.DateField(null=True),
        ),
    ]
