# Generated by Django 4.0.2 on 2022-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_caracterizacaodecurso_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacaodeevento',
            name='duracao_do_evento_em_numero_de_dias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacaodeevento',
            name='numero_da_edicao_do_evento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacaodeevento',
            name='quantitativo_de_publico',
            field=models.IntegerField(null=True),
        ),
    ]
