# Generated by Django 4.0.2 on 2022-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_caracterizacaodeevento_duracao_do_evento_em_numero_de_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacaodecurso',
            name='periodos_de_oferta_do_curso_nos_proximos_5_anos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacaodeprojeto',
            name='duracao_pretendida_do_projeto',
            field=models.IntegerField(null=True),
        ),
    ]
